# @package _global_

# Musdb + extra tracks
dset:
  wav: /home/user/data/
  samplerate: 44100
  channels: 2
  sources: ['bass', 'non_bass']
epochs: 320
max_batches: 300
batch_size: 8

misc:
  num_workers: 4

test:
  save: False
  best: True
  workers: 0
  every: 1
  split: true
  shifts: 0
  overlap: 0.25
  sdr: false
  metric: 'loss'  # metric used for best model selection on the valid set, can also be nsdr
  nonhq:   # path to non hq MusDB for evaluation